// blog-posts/share-component-across-front-end-framework-using-nx-and-web-component/exemple/demo-shared/apps/demo-react/src/app/app.tsx

import { useEffect, useRef } from 'react';

import { DemoCounterElement, DemoProfileElement } from '@demo-shared/demo-library';

import styles from './app.module.css';

export function App() {
  const person = {
    firstName: 'Jack',
    lastName: 'Doe'
  }
  const counter = useRef<DemoCounterElement>(null);
  const profile = useRef<DemoProfileElement>(null);

  useEffect(function () {
    if(counter.current) {
      counter.current.counter = 5
    }
    if(profile.current) {
      profile.current.person = person 
    }
  }, []);
  
  return (
    <div className={styles.app}>
      <demo-title title={"React"} />
      <demo-title-colored title={"React"} />
      <demo-object dataPerson={JSON.stringify(person)}/>
      <demo-profile ref={profile}/>
      <demo-counter ref={counter} userClick={(e: Event) =>  console.log(e)} />
    </div>
  );
}

export default App;

// blog-posts/share-component-across-front-end-framework-using-nx-and-web-component/exemple/demo-shared/apps/demo-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'demo-shared-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less'],
})
export class AppComponent {
  title = 'demo-angular';
  JSON = JSON;

  person = {
    firstName: 'Jack',
    lastName: 'Doe'
  }

  clicked(event: Event) {
    console.log(event)
  }
}

<demo-title [title]="'Angular'"></demo-title>
<demo-title-colored [title]="'Angular'"></demo-title-colored>
<demo-object [attr.data-person]="JSON.stringify(person)"></demo-object>
<demo-profile [person]="person"></demo-profile>
<demo-counter [counter]="3" (userClick)="clicked($event)"></demo-counter>
